<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62795" started-at="2018-10-06T08:29:57Z" finished-at="2018-10-06T08:31:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62795" started-at="2018-10-06T08:29:57Z" finished-at="2018-10-06T08:31:00Z">
      <class name="testPackage.TestClass">
        <test-method status="PASS" signature="testInit()[pri:0, instance:testPackage.TestClass@1794d431]" name="testInit" is-config="true" duration-ms="203" started-at="2018-10-06T08:29:57Z" finished-at="2018-10-06T08:29:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInit -->
        <test-method status="PASS" signature="setUpTest(java.lang.reflect.Method)[pri:0, instance:testPackage.TestClass@1794d431]" name="setUpTest" is-config="true" duration-ms="16402" started-at="2018-10-06T08:29:58Z" finished-at="2018-10-06T08:30:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testPackage.TestClass.EMI_Calculator() throws java.awt.HeadlessException,java.awt.AWTException,java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="FAIL" signature="EMI_Calculator()[pri:0, instance:testPackage.TestClass@1794d431]" name="EMI_Calculator" duration-ms="18939" started-at="2018-10-06T08:30:14Z" description="User story2 : Verify whether the Auto Loan calculator generated values are correct" finished-at="2018-10-06T08:30:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: values not the same expected [for 24 months at 4.5% APR.] but found [for 24 months at 0.0% APR.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: values not the same expected [for 24 months at 4.5% APR.] but found [for 24 months at 0.0% APR.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at pagesPackages.AutoLoanCalculator.ValidateCalculator(AutoLoanCalculator.java:254)
at testPackage.TestClass.EMI_Calculator(TestClass.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EMI_Calculator -->
        <test-method status="PASS" signature="tearDownTest(org.testng.ITestResult)[pri:0, instance:testPackage.TestClass@1794d431]" name="tearDownTest" is-config="true" duration-ms="1" started-at="2018-10-06T08:30:33Z" finished-at="2018-10-06T08:30:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=EMI_Calculator status=FAILURE method=TestClass.EMI_Calculator()[pri:0, instance:testPackage.TestClass@1794d431] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method status="PASS" signature="setUpTest(java.lang.reflect.Method)[pri:0, instance:testPackage.TestClass@1794d431]" name="setUpTest" is-config="true" duration-ms="13685" started-at="2018-10-06T08:30:33Z" finished-at="2018-10-06T08:30:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testPackage.TestClass.Validate_Price() throws java.awt.HeadlessException,java.awt.AWTException,java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="Validate_Price()[pri:0, instance:testPackage.TestClass@1794d431]" name="Validate_Price" duration-ms="13262" started-at="2018-10-06T08:30:47Z" description="User story 1: Check error message is displayed if price not entered" finished-at="2018-10-06T08:31:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_Price -->
        <test-method status="PASS" signature="tearDownTest(org.testng.ITestResult)[pri:0, instance:testPackage.TestClass@1794d431]" name="tearDownTest" is-config="true" duration-ms="0" started-at="2018-10-06T08:31:00Z" finished-at="2018-10-06T08:31:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Validate_Price status=SUCCESS method=TestClass.Validate_Price()[pri:0, instance:testPackage.TestClass@1794d431] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method status="PASS" signature="clearUp()[pri:0, instance:testPackage.TestClass@1794d431]" name="clearUp" is-config="true" duration-ms="282" started-at="2018-10-06T08:31:00Z" finished-at="2018-10-06T08:31:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearUp -->
      </class> <!-- testPackage.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
